<a href="https://colab.research.google.com/github/FarhanFansuri/Tensorflow-repo/blob/alladin-persson/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Apa itu Tensor
Tensor adalah array multidimensi

In [1]:
import tensorflow as tf

## Initialization of tensor

In [15]:
x = tf.constant(4,dtype=tf.int16, shape=(1,1))
print(x)

y = tf.constant([[1,2,3],[4,5,6]], dtype=tf.int16)
print(y)

z = tf.ones((3,3))
print(z)

a = tf.zeros((2,3))
print(a)

i = tf.eye(3)
print(i)

r = tf.random.normal((3,3),mean = 0.0, stddev=1.0)
print(r)

rang = tf.range(6)
print(rang)

c = tf.cast(rang,dtype=tf.float32)
print(c)

tf.Tensor([[4]], shape=(1, 1), dtype=int16)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int16)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.16465136 -0.7339975   1.9737052 ]
 [-0.23461331 -0.33044845 -0.62707347]
 [-0.7601108  -0.5068668   0.6418268 ]], shape=(3, 3), dtype=float32)
tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int32)
tf.Tensor([0. 1. 2. 3. 4. 5.], shape=(6,), dtype=float32)


## mathematical operations

In [17]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

z = tf.add(x,y)
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
